<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>PerfTest</AssemblyName>
    <RootNamespace>Sentinel.Perf</RootNamespace>
    <StartupObject>Sentinel.PerfTest</StartupObject>
    <Optimize>true</Optimize>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="PerfTest.cs" />
    <Compile Include="..\src\Cmd.cs" />
    <Compile Include="..\src\Collector.cs" />
  </ItemGroup>
</Project>