<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>IconGenTool</AssemblyName>
    <RootNamespace>Sentinel</RootNamespace>
    <StartupObject>Sentinel.Program</StartupObject>
  </PropertyGroup>
</Project>