<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>Sentinel-Ccufo</AssemblyName>
    <Product>Sentinel-Ccufo</Product>
    <AssemblyTitle>Sentinel-Ccufo</AssemblyTitle>
    <Description>SMB 端口暴露实时监控与一键处置工具</Description>
    <RootNamespace>Sentinel</RootNamespace>
    <ApplicationIcon>..\assets\sentinel.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <SatelliteResourceLanguages>zh-Hans</SatelliteResourceLanguages>
    <DebugType>none</DebugType>
    <Optimize>true</Optimize>
    <TieredPGO>true</TieredPGO>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <ConcurrentGarbageCollection>false</ConcurrentGarbageCollection>
  </PropertyGroup>

</Project>